# Generated by Django 4.2.16 on 2026-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
