# Generated by Django 4.2.24 on 2026-10-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_modulecategory_role_module_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FhMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_route_type_id', models.IntegerField(blank=True, null=True)),
                ('menu_name', models.CharField(blank=True, max_length=127, null=True)),
                ('menu_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_status', models.BooleanField(blank=True, default=True, null=True)),
                ('menu_sub_status', models.IntegerField(default=0)),
                ('menu_route', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_group', models.CharField(blank=True, max_length=55, null=True)),
                ('menu_mdl_id', models.IntegerField(blank=True, null=True)),
                ('menu_sequence', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_p', models.ForeignKey(blank=True, db_column='menu_p_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='accounts.fhmenu')),
            ],
            options={
                'db_table': 'fh_menus',
                'ordering': ['menu_sequence'],
            },
        ),
    ]
