# Generated by Django 4.2.24 on 2026-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_guardian_name_customuser_guardian_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('pending', 'Pending'), ('dropped', 'Dropped'), ('graduated', 'Graduated')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=20, null=True),
        ),
    ]
