# Generated by Django 4.2.24 on 2026-10-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_admission_date_customuser_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initial_password',
            field=models.CharField(blank=True, help_text='Stores the initial raw password for super admin to view', max_length=255, null=True),
        ),
    ]
