# Generated by Django 4.2.24 on 2026-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_module_options_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(default='fa-solid fa-circle', help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, help_text="Django URL name (e.g., 'user_list')", max_length=100, null=True),
        ),
    ]
